# Generated by Django 4.2.2 on 2023-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Email",
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Name",
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
